server:
  port: 8080

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/qqsite?useSSL=false&useUnicode=true&characterEncoding=UTF-8
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: Passw0rd

mybatis:
  mapper-locations: classpath:mapping/*Mapper.xml
  type-aliases-package: com.icbc.fmtesting.entity